# Generated by Django 4.2.5 on 2023-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'payment_api_conta',
            },
        ),
    ]
