# Generated by Django 4.2.5 on 2023-10-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficiario', models.CharField(max_length=100)),
                ('remetente', models.CharField(max_length=100)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='conta',
            field=models.ForeignKey(
                to='payment_api.Conta',
                on_delete=models.CASCADE,
            ),
        ),
    ]
